version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: paqueteria_postgres
    environment:
      POSTGRES_DB: paqueteria
      POSTGRES_USER: paqueteria_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - paqueteria_network
    restart: unless-stopped

  redis:
    image: redis:7.0-alpine
    container_name: paqueteria_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"
    networks:
      - paqueteria_network
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paqueteria_app
    environment:
      - DATABASE_URL=postgresql://paqueteria_user:${POSTGRES_PASSWORD}@postgres:5432/paqueteria
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - SMTP_HOST=taylor.mxrouting.net
      - SMTP_PORT=587
      - SMTP_USER=guia@papyrus.com.co
      - SMTP_PASSWORD=90@5fmCU%gabP4%*
      - SMTP_FROM_NAME=PAQUETES EL CLUB
      - LIWA_API_KEY=${LIWA_API_KEY}
      - LIWA_PHONE_NUMBER=${LIWA_PHONE_NUMBER}
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    ports:
      - "8001:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - paqueteria_network
    restart: unless-stopped

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paqueteria_celery_worker
    command: celery -A src.celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://paqueteria_user:${POSTGRES_PASSWORD}@postgres:5432/paqueteria
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - SMTP_HOST=taylor.mxrouting.net
      - SMTP_PORT=587
      - SMTP_USER=guia@papyrus.com.co
      - SMTP_PASSWORD=90@5fmCU%gabP4%*
      - LIWA_API_KEY=${LIWA_API_KEY}
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      - postgres
      - redis
    networks:
      - paqueteria_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: paqueteria_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./uploads:/var/www/uploads
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - paqueteria_network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: paqueteria_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - paqueteria_network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: paqueteria_grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - paqueteria_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  paqueteria_network:
    driver: bridge
