version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: paqueteria_v31_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./code/nginx/conf.d:/etc/nginx/conf.d
      - ./code/static:/app/static
      - ./code/uploads:/app/uploads
      - ./ssl:/etc/nginx/ssl
    networks:
      - paqueteria_network
    restart: unless-stopped
    depends_on:
      - app
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
    environment:
      TZ: America/Bogota

  redis:
    image: redis:7-alpine
    container_name: paqueteria_v31_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"
    networks:
      - paqueteria_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
    environment:
      TZ: America/Bogota

  app:
    build:
      context: ./code
      dockerfile: Dockerfile
    container_name: paqueteria_v31_app
    env_file:
      - ./code/env.aws
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://jveyes:a%3FHC%212.%2A1%23%3F%5B%3D%3D%3A%7C289qAI%3D%29%23V4kDzl%24@ls-abe25e9bea57818f0ee32555c0e7b4a10e361535.ctobuhtlkwoj.us-east-1.rds.amazonaws.com:5432/paqueteria}
      - REDIS_URL=redis://redis:6379/0
      - TZ=America/Bogota
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./code/src:/app/src
      - ./code/templates:/app/templates
      - ./code/static:/app/static
      - ./code/uploads:/app/uploads
      - ./code/logs:/app/logs
      - ./code/database:/app/database
      - ./code/scripts:/app/scripts
      - ./code/tests:/app/tests
      - ./code/docs:/app/docs
    networks:
      - paqueteria_network
    restart: unless-stopped
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  celery_worker:
    build:
      context: ./code
      dockerfile: Dockerfile
    container_name: paqueteria_v31_celery_worker
    command: celery -A src.celery_app worker --loglevel=info --concurrency=2
    env_file:
      - ./code/env.aws
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://jveyes:a%3FHC%212.%2A1%23%3F%5B%3D%3D%29%23V4kDzl%24@ls-abe25e9bea57818f0ee32555c0e7b4a10e361535.ctobuhtlkwoj.us-east-1.rds.amazonaws.com:5432/paqueteria}
      - REDIS_URL=redis://redis:6379/0
      - TZ=America/Bogota
    volumes:
      - ./code/src:/app/src
      - ./code/templates:/app/templates
      - ./code/static:/app/static
      - ./code/uploads:/app/uploads
      - ./code/logs:/app/logs
      - ./code/database:/app/database
      - ./code/scripts:/app/scripts
      - ./code/tests:/app/tests
      - ./code/docs:/app/docs
    networks:
      - paqueteria_network
    restart: unless-stopped
    depends_on:
      - redis
      - app
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "celery", "-A", "src.celery_app", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  redis_data:

networks:
  paqueteria_network:
    driver: bridge
