"""fix password reset tokens table

Revision ID: 035f10409271
Revises: 8577f765fb12
Create Date: 2025-08-29 07:10:45.441174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '035f10409271'
down_revision = '8577f765fb12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Agregar columnas faltantes a password_reset_tokens
    op.add_column('password_reset_tokens', sa.Column('is_used', sa.Boolean(), nullable=True))
    op.execute("UPDATE password_reset_tokens SET is_used = false WHERE is_used IS NULL")
    op.alter_column('password_reset_tokens', 'is_used', nullable=False)
    
    op.add_column('password_reset_tokens', sa.Column('used_at', sa.DateTime(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('password_reset_tokens', 'used_at')
    op.drop_column('password_reset_tokens', 'is_used')
    # ### end Alembic commands ###
