"""add phone validation fields

Revision ID: 0cadd8c3db49
Revises: 004_add_tracking_code_to_announcements
Create Date: 2024-12-19 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cadd8c3db49'
down_revision = '004_add_tracking_code_to_announcements'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Agregar campos para mejor manejo de teléfonos
    op.add_column('customers', sa.Column('country_code', sa.String(length=5), nullable=True, server_default='+57'))
    op.add_column('customers', sa.Column('phone_formatted', sa.String(length=25), nullable=True))
    op.add_column('customers', sa.Column('phone_country', sa.String(length=50), nullable=True, server_default='Colombia'))
    
    # Crear índice para búsquedas por país
    op.create_index('idx_customer_country', 'customers', ['country_code'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Eliminar índice
    op.drop_index('idx_customer_country', table_name='customers')
    
    # Eliminar columnas
    op.drop_column('customers', 'phone_country')
    op.drop_column('customers', 'phone_formatted')
    op.drop_column('customers', 'country_code')
    
    # ### end Alembic commands ###
